version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: api
    image: api_dev
    ports:
      - "5240:5240"
    volumes:
      - './backend/:/src/'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5240;
    restart: always